#!/bin/bash

curl --create-dirs "https://wonder.cdc.gov/wonder/sci_data/datasets/zipctyA.zip" -o "zipctys/zipctyA.zip" "https://wonder.cdc.gov/wonder/sci_data/datasets/zipctyB.zip" -o "zipctys/zipctyB.zip"

unzip "zipctys/zipctyA.zip" -d zipctys
unzip "zipctys/zipctyB.zip" -d zipctys

(echo '1794315,s/  /GA'; echo 'w')|ed -s "zipctys/zipcty4"
